version: '3'
services:
  jekyll:
    image: coronablogbr/devenv
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/blog
    tty: true
    command: octopod serve --host 0.0.0.0 --force_polling --livereload --config _config.yml,_config_dev.yml,_config_dev_toolbox.yml